// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaZAAI4A-da9aBQ2S2NMLkgC7w-DKXvVw',
    appId: '1:46506409715:web:233caa186362cc983a4186',
    messagingSenderId: '46506409715',
    projectId: 'weather-app-de8d9',
    authDomain: 'weather-app-de8d9.firebaseapp.com',
    storageBucket: 'weather-app-de8d9.firebasestorage.app',
    measurementId: 'G-3TBKR5RL7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtu_hfdrKAV6x-sFijSGpuFtrYuk24IKM',
    appId: '1:46506409715:android:940916ff3482df053a4186',
    messagingSenderId: '46506409715',
    projectId: 'weather-app-de8d9',
    storageBucket: 'weather-app-de8d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGSQP-R2C1fhnBKUOuXbscXTZFJAQx0iE',
    appId: '1:46506409715:ios:10d78b02097016f93a4186',
    messagingSenderId: '46506409715',
    projectId: 'weather-app-de8d9',
    storageBucket: 'weather-app-de8d9.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGSQP-R2C1fhnBKUOuXbscXTZFJAQx0iE',
    appId: '1:46506409715:ios:10d78b02097016f93a4186',
    messagingSenderId: '46506409715',
    projectId: 'weather-app-de8d9',
    storageBucket: 'weather-app-de8d9.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaZAAI4A-da9aBQ2S2NMLkgC7w-DKXvVw',
    appId: '1:46506409715:web:e37fe4deb1712fd53a4186',
    messagingSenderId: '46506409715',
    projectId: 'weather-app-de8d9',
    authDomain: 'weather-app-de8d9.firebaseapp.com',
    storageBucket: 'weather-app-de8d9.firebasestorage.app',
    measurementId: 'G-CCFN36LYDD',
  );
}
